tap "hashicorp/tap"
tap "homeport/tap"
brew "python@3.14"
brew "yq"
brew "eza"
brew "ghostscript"
brew "go"
brew "helm"
brew "htop"
brew "k9s"
brew "kubernetes-cli"
brew "clusterctl"
brew "kustomize"
brew "podman"
brew "docker"
brew "neovim"
brew "nmap"
brew "node"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "wget"
brew "zoxide"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/packer"
brew "homeport/tap/havener"
brew "fzf"
brew "docker-compose"
brew "templ"
brew "d2"
brew "presenterm"
brew "gh"
brew "restic"
brew "anomalyco/tap/opencode"
cask "aldente"
cask "alt-tab"
cask "appcleaner"
cask "dbeaver-community"
cask "discord"
cask "drawio"
cask "figma"
cask "firefox"
cask "flameshot"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "inkscape"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "windows-app"
cask "mysqlworkbench"
cask "nextcloud"
cask "notion"
cask "openvpn-connect"
cask "rectangle"
cask "sol"
cask "spotify"
cask "the-unarchiver"
cask "thunderbird"
cask "vlc"
cask "sonos"
cask "pgadmin4"
cask "visual-studio-code"

hostname = `hostname -s`.strip

# unless could be also a viable alternative
if hostname == "toshiro" or hostname == "mac-mini"
    cask "keepassxc"
    cask "google-chrome"
else
    cask "microsoft-teams"
    cask "slack"
end
